apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-jpagenerator
spec:
  type: ClusterIP
  selector:
    app: {{ include "myapp.fullname" . }}-jpagenerator
  ports:
      - port: 80
        targetPort: 8080