spring:
  ai:
    azure:
      openai:
        api-key: ${YOUR_AZURE_API_KEY}
        endpoint: https://test-open-ai-dep.openai.azure.com/
        chat:
          options:
            deployment-name: gpt-4.1