apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  # Use LoadBalancer type to expose the service externally via an Azure Load Balancer
  type: LoadBalancer
  selector:
    app: spring-app # This must match the 'app' label in the deployment metadata
  ports:
    - protocol: TCP
      port: 80 # The port where the service is accessible externally (e.g., in a browser)
      targetPort: 8080 # The port the container is listening on (from the deployment.yaml)
